/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { VikaService } from "../vika.service";
import { VikaCreateInput } from "./VikaCreateInput";
import { Vika } from "./Vika";
import { VikaFindManyArgs } from "./VikaFindManyArgs";
import { VikaWhereUniqueInput } from "./VikaWhereUniqueInput";
import { VikaUpdateInput } from "./VikaUpdateInput";

export class VikaControllerBase {
  constructor(protected readonly service: VikaService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Vika })
  async createVika(@common.Body() data: VikaCreateInput): Promise<Vika> {
    return await this.service.createVika({
      data: {
        ...data,

        mor: data.mor
          ? {
              connect: data.mor,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        mor: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Vika] })
  @ApiNestedQuery(VikaFindManyArgs)
  async vikas(@common.Req() request: Request): Promise<Vika[]> {
    const args = plainToClass(VikaFindManyArgs, request.query);
    return this.service.vikas({
      ...args,
      select: {
        createdAt: true,
        id: true,

        mor: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Vika })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async vika(
    @common.Param() params: VikaWhereUniqueInput
  ): Promise<Vika | null> {
    const result = await this.service.vika({
      where: params,
      select: {
        createdAt: true,
        id: true,

        mor: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Vika })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateVika(
    @common.Param() params: VikaWhereUniqueInput,
    @common.Body() data: VikaUpdateInput
  ): Promise<Vika | null> {
    try {
      return await this.service.updateVika({
        where: params,
        data: {
          ...data,

          mor: data.mor
            ? {
                connect: data.mor,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          mor: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Vika })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteVika(
    @common.Param() params: VikaWhereUniqueInput
  ): Promise<Vika | null> {
    try {
      return await this.service.deleteVika({
        where: params,
        select: {
          createdAt: true,
          id: true,

          mor: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
